### ISSUE TITLE
Problems with WordPress.

### ISSUE THREAD

**Issue by Suleman-Elahi** [sandoche/Darkmode.js#1]
1: Widget doesn't show up on some themes.
2: Widget is not clickable on some themes.
3: Webpage Title and Website title are being darked out after activating it.

![image](https://user-images.githubusercontent.com/24384996/59824393-9949e600-934e-11e9-8944-fc31c443ef71.png)

--> **_Only worked for me on WordPress's Twenty Nineteen Theme_**

Tip: Add topics to the GitHub repo.

**Comment by sandoche** [comment]
Have you tried to debug with z-index ?
https://github.com/sandoche/Darkmode.js#debug

**Comment by meisterleise** [comment]
I've tested it on 2 WP websites right now. It doesn't work.
What a pitty!! :(

**Comment by sandoche** [comment]
Have you tried this:
```css
.darkmode-layer, .darkmode-toggle {
  z-index: 500;
}
```

**Comment by meisterleise** [comment]
@sandoche of course!

**Comment by sandoche** [comment]
I don't find the button.
Also don't think it will solve the problem but you can try using this Wordpress plugins:
https://wordpress.org/plugins/blackout-darkmode-widget/
https://wordpress.org/plugins/darkmode/
