### ISSUE TITLE
Isolation doesn't work when Position is relative or transform is applied

### ISSUE THREAD

**Issue by Thaiten** [sandoche/Darkmode.js#12]
The Dark-Mode exclusion works perfectly on all "normal" objects. But when I add either a position of fixed, sticky, absolute or relative, It doesn't anymore. Same with transforms etc.

**Comment by sandoche** [comment]
Try using this on your element:
```
.darkmode--activated .element {
  mix-blend-mode: difference;
}
```

**Comment by Thaiten** [comment]
Yup, that works! Was that on the website already and I just didn't see it?

**Comment by sandoche** [comment]
Yep.

**Comment by k6xiao** [comment]
`
/*这个依然不能生效*/
.darkmode--activated .element {
  mix-blend-mode: difference;
}

/*这个属性可以生效，但是发现会有一瞬间的闪动*/
.darkmode--activated .element {
  filter: invert(1) hue-rotate(180deg);
}

`

**Comment by k6xiao** [comment]
这个依然不能生效：
`
.darkmode--activated .element {
mix-blend-mode: difference;
}
`
这个属性可以生效，但是发现会有一瞬间的闪动：
`
.darkmode--activated .element {
filter: invert(1) hue-rotate(180deg);
}
`
