### ISSUE TITLE
Request: demo with switch toggle

### ISSUE THREAD

**Issue by coliff** [sandoche/Darkmode.js#13]
It'd be great to see a simple demo with a switch toggle for turning dark-mode on. I'd like to use it with the Bootstrap Custom Switch but unsure of the code to add to it.
https://getbootstrap.com/docs/4.3/components/forms/#switches

**Comment by coliff** [comment]
Update: I got it working with the switch  - was easier than I thought :-)
https://codepen.io/coliff/pen/ewrvKJ
But it doesn't save the swicth state between different pages. If anyone knows how to add that and could fork that Codepen or paste the code here that'd be great.

**Comment by sandoche** [comment]
Here it is:
https://codepen.io/sandoche/pen/PrLKdg
