### ISSUE TITLE
Label option not working

### ISSUE THREAD

**Issue by biswajit-paul** [sandoche/Darkmode.js#14]
I followed same instructions mentioned in https://github.com/sandoche/Darkmode.js. But somehow label is not working.

Demo: https://codepen.io/johndoe007/pen/gNdOrN

**Comment by hexandcube** [comment]
Replace:
```js
new Darkmode().showWidget( options );
```
with:
```js
const darkmode = new Darkmode(options);
darkmode.showWidget();
```

**Comment by the-mcnaveen** [comment]
Still same issue buddy :cry: 

Code:
![Selection_012](https://user-images.githubusercontent.com/8493007/71244762-41119200-2339-11ea-8a31-d0d326d0af62.png)

In Browser 
![Selection_013](https://user-images.githubusercontent.com/8493007/71244779-4c64bd80-2339-11ea-9259-494de6b3b156.png)
