### ISSUE TITLE
Emojis change its color in dark mode

### ISSUE THREAD

**Issue by martincomito** [sandoche/Darkmode.js#18]
I have a GatsbyJS blog and I can't make the emojis remain their original color in the dark mode, I tried everything from the darkmodejs documentation but I still can't achieve it. Is there any way to add the darkmode-ignore css class to an emoji in the markdown text?

Thanks!

**Comment by Turkyden** [comment]
Here is react-darkreader.

https://react-darkreader.vercel.app/
