### ISSUE TITLE
Double click will give you a Ellipse

### ISSUE THREAD

**Issue by samcompu** [sandoche/Darkmode.js#24]
![:)](https://i.loli.net/2019/11/08/wiaxGH3IvJtSjug.png)

**Comment by bdthemes** [comment]
Same issue for me too!

**Comment by shahidul24** [comment]
I Got also same Issue.

![image](https://user-images.githubusercontent.com/35867332/69600264-33b6ff80-103a-11ea-83a1-8f2955a87486.png)

**Comment by MrSkwiggs** [comment]
Duplicate of #7
