### ISSUE TITLE
Add an option to automatically switch to darkmode if it's enabled in the device

### ISSUE THREAD

**Issue by sandoche** [sandoche/Darkmode.js#3]
A feature idea:
* Automatically activate the darkmode if the device is

Resources:
https://stackoverflow.com/questions/50840168/how-to-detect-if-the-os-is-in-dark-mode-in-browsers

**Comment by oznorts** [comment]
Here's some Webkit information on this: https://webkit.org/blog/8840/dark-mode-support-in-webkit/

**Comment by sandoche** [comment]
It's now implemented in the version 1.4.0
