### ISSUE TITLE
Usage without the widget displays a button

### ISSUE THREAD

**Issue by sandoche** [sandoche/Darkmode.js#31]
I use Darkmode.js programmatically without displaying the widget, since the version 1.5.4 I have the following bug (a little empty button appearing)

![Capture d’écran de 2020-01-02 11-18-06](https://user-images.githubusercontent.com/3635348/71662764-e887bf00-2d52-11ea-8987-8908cab4ff5f.png)

**Comment by hexandcube** [comment]
I have the same problem. I can't hide the button with CSS since it doesn't have any class, or id.

![image](https://user-images.githubusercontent.com/41151156/71781565-7f14e400-2fd0-11ea-854d-df91fa4faef9.png)

**Comment by tmbv93** [comment]
I also had this issue! 
I think it started here: #27 
`const button = document.createElement('button');`

Added a PR #34 to fix it!

**Comment by sandoche** [comment]
Fixed in #34
