### ISSUE TITLE
Darkmode body color?

### ISSUE THREAD

**Issue by SteepNet** [sandoche/Darkmode.js#33]
Hi! How do I set the background body color I need?
default color = #000000
need  = #222222

**Comment by SteepNet** [comment]
this project die?
no more support?

**Comment by sandoche** [comment]
In options:
```js
var options = {
  backgroundColor: '#fff'
}
```

This is the default background support try maybe `#DDDDDD`

**Comment by SteepNet** [comment]
> In options:
> 
> ```js
> var options = {
>   backgroundColor: '#fff'
> }
> ```
> 
> This is the default background support try maybe `#DDDDDD`

Yes it works fine
mixColor: '#DDDDDD'
