### ISSUE TITLE
Releasing "releases"?

### ISSUE THREAD

**Issue by optimocha** [sandoche/Darkmode.js#36]
Hi @sandoche,

Author of the "Darkmode" WordPress plugin here. Any chance you could submit new releases with changelogs, so we can "watch" the repo and get notified with new releases? Right now I don't even know which version is darkmode.js on.

**Comment by sandoche** [comment]
Sounds like a good idea.
I will do that for the next release.

For now you can check the changelog here:
https://github.com/sandoche/Darkmode.js/blob/master/CHANGELOG.md

**Comment by optimocha** [comment]
Thanks man!
