### ISSUE TITLE
Using snippet won't work.

### ISSUE THREAD

**Issue by keanuplayz** [sandoche/Darkmode.js#37]
For my own website, I decided to give this a shot.

I added the snippet that was given to me to my own page:
```html
<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.5/lib/darkmode-js.min.js"></script>
<script>
  new Darkmode().showWidget();
</script>
```

But to my surprise, nothing happened.

I checked the console, and found this:

```
darkmode-js.min.js:1 Uncaught TypeError: Cannot read property 'classList' of null
    at new e (darkmode-js.min.js:1)
```

I haven't done anything weird.

I even created a new html document with nothing in it except a default template with some text, added the snippet, and nothing happened.

Any help?

**Comment by sandoche** [comment]
It may be because you use it without a localserver it may happen if you open directly the html file.

**Comment by keanuplayz** [comment]
I am using a local server to preview my files.

**Comment by sandoche** [comment]
Do you have any extension blockcking things ? please try with another browser maybe.

**Comment by SaadAhmadSaddiqui** [comment]
Hi, Sandoche. I am facing the same problem. I put the snippet in the head tag of the master page in ASP.Net and it doesn't work. The error is the same as the one above on both Chrome and Edge.

`darkmode-js.min.js:1 Uncaught TypeError: Cannot read property 'classList' of null
    at new e (darkmode-js.min.js:1)`

**Comment by StafDehat** [comment]
I think the reason this is happening, is because the script attempts to append a DOM object before the DOM tree has loaded.
You'll need to call showWidget() *after* the page has loaded - you can do that by putting it inside an event listener for "load".
I made a PR to update the readme as such - see here for details:
https://github.com/sandoche/Darkmode.js/pull/47/files

**Comment by keanuplayz** [comment]
That indeed managed to fix my issue a couple of days back. (see [here](https://github.com/keanuplayz/keanucode.ml/commit/b43f03720c1bc237db08b9db4a4c3a6f07e80f99#diff-390c44e829290dfd2e6ced208641e606R13-R20))
I believe this can *finally* be closed now that we have a definite fix.
