### ISSUE TITLE
How to add switchDarkmode to the menu？

### ISSUE THREAD

**Issue by manic-depressive** [sandoche/Darkmode.js#38]
I'm not a programmer, but I want to add switchDarkmode to the menu.I don't know how? My wordpress theme is TwentyTwenty. In addition, this DarkMode is not work on search bar. Thanks

**Comment by manic-depressive** [comment]
My website is https://dailylo.pro/  Now，I'm using blackout darkmode widget.

**Comment by sandoche** [comment]
The link does not work.
