### ISSUE TITLE
Darkmode toggle is behind other HTML element

### ISSUE THREAD

**Issue by eliasbenb** [sandoche/Darkmode.js#41]
So I can't click the toggle because it's behind an HTML element.

I tried making a CSS file and putting this:
```
.darkmode-layer, .darkmode-toggle{
    z-index: 999;
}
```

But I have 0 experience with CSS so I'm not sure if that's correct. Any ideas?

**Comment by curtismchale** [comment]
Do you have a link to the site? I did have to use CSS as above and it worked for me.

**Comment by eliasbenb** [comment]
> Do you have a link to the site? I did have to use CSS as above and it worked for me.

Thank you for the reply. The website is https://eliasbenb.github.io/ any help would be appreciated.
