### ISSUE TITLE
Darkmode.js, possible issue with jQuery and Bootstrap 4

### ISSUE THREAD

**Issue by ashmlk** [sandoche/Darkmode.js#44]
Hi, I tried adding        ```
 <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.6/lib/darkmode-js.min.js"></script>
        <script>
        $(document).ready(function () {
          var options = {
          bottom: '64px', // default: '32px'
          right: 'unset', // default: '32px'
          left: '32px', // default: 'unset'
          time: '0.5s', // default: '0.3s'
          mixColor: '#fff', // default: '#fff'
          backgroundColor: '#fff',  // default: '#fff'
          buttonColorDark: '#100f2c',  // default: '#100f2c'
          buttonColorLight: '#fff', // default: '#fff'
          saveInCookies: false, // default: true,
          label: '🌓', // default: ''
          autoMatchOsTheme: true // default: true
        }
        const darkmode = new Darkmode(options);
        darkmode.showWidget();
        });
        
        </script>
```
To my website and It seems that it is not working at all, I simply cannot click on the Dakrmode button. Is there anything that can help me fix this issue?

**Comment by extant1** [comment]
I had the same issue and adding the following line into my .css file fixed the issue.

`.darkmode-layer, .darkmode-toggle {
  z-index: 500;
}
`
