### ISSUE TITLE
Darkmode gives back text on black background with MathJax

### ISSUE THREAD

**Issue by purusharths** [sandoche/Darkmode.js#45]
Hi

I'm using darkmode.js which has a lot of mathematical formulae - rendered with mathjax. However, all those formulae do not change the colour to white when dark mode is switched on 

With white [background](https://i.imgur.com/MBEOIP2.png)
With [Darkmode switched activated](https://i.imgur.com/rKCzEZ9.png)

Is there a way around it?

**Comment by sandoche** [comment]
Try the fix I recommended here #52
