### ISSUE TITLE
Starting in Dark Mode

### ISSUE THREAD

**Issue by bryan** [sandoche/Darkmode.js#50]
Is there a way to start it in dark mode via the options or to force dark mode to be the default on initial load?

**Comment by sandoche** [comment]
1. You need to disable the `autoMatchOsTheme` to avoid to automatically activate darkmode if the browser is in darkmode.
2. Then you need to programatically toggle darkmode using the `toggle();` method

So basically you need to do something like this
```js
const options = {
  autoMatchOsTheme: false
}

const darkmode = new Darkmode(options);
darkmode.showWidget();
darkmode.toggle();
```

**Comment by bryan** [comment]
Thanks, solution is workable.

**Comment by colvdv** [comment]
I am working with the basic instructions for HTML input and am having a hard time figuring this out. I'm just not sure where to insert this code at.

Here is what I am working with:
```
<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
<script>
  function addDarkmodeWidget() {
    new Darkmode().showWidget();
  }
  window.addEventListener('load', addDarkmodeWidget);
</script>
```

Assistance is greatly appreciated!

Note: I am looking to disable darkmode by default. I want site visitors to have to turn it on themselves if they want it.
