### ISSUE TITLE
Broken on Mobile Firefox 79.0.5

### ISSUE THREAD

**Issue by tannercollin** [sandoche/Darkmode.js#53]
I'm sure this is an issue with the new Firefox update, but I thought it would be best to mention:

![photo_2020-08-30_01-26-45](https://user-images.githubusercontent.com/6752449/91653673-13502180-ea60-11ea-9c10-87c153051d5d.jpg)

**Comment by sandoche** [comment]
@tannercollin is it fixed?

**Comment by tannercollin** [comment]
Yup, seems to work fine now.
