### ISSUE TITLE
not working with bootstrap framework

### ISSUE THREAD

**Issue by xujaan** [sandoche/Darkmode.js#58]
it's only change the background, any others component still the same

**Comment by sandipsubedi** [comment]
I am seeing the same issue. Wondering if anyone else is able to use it on Bootstrap4

**Comment by sandipsubedi** [comment]
This solved most of the issue, still seeing some issues with the button and labels:
```
.darkmode-layer, .darkmode-toggle { z-index: 500; }
```

Got it from here:
https://github.com/sandoche/Darkmode.js/issues/44
