### ISSUE TITLE
Saving Mode

### ISSUE THREAD

**Issue by markwsac** [sandoche/Darkmode.js#66]
When I disconnect my app and connect it again darkmode shows the last set mode. How can i disable it so that darkmode is inactive while app initiates?

`**<input id="darktoggle" type="checkbox"/>**
` 
```
          const options = {autoMatchOsTheme: false}
          const darkmode =  new Darkmode(options);

          $('#darktoggle').click(function(){
              darkmode.toggle();
          });

           if (darkmode.isActivated()) {
              document.getElementById('darktoggle').checked = true;
            }
          else {
                document.getElementById('darktoggle').checked = false;
          }
```

**Comment by sandoche** [comment]
You need to play with this options:

```js
const options = {
  saveInCookies: false, // default: true,
  autoMatchOsTheme: true // default: true
}
```

`saveInCookies` is the one that remember the darkmode last choice.
`autoMatchOsTheme` will trigger automatically the OS theme!
